### ISSUE TITLE
Mistaken editor preview with complex superscript/subscript expressions

### ISSUE THREAD

**Issue by jkseppan** [digabi/rich-text-editor#333] opened 2021-07-30 07:28 UTC
Here I am entering the expression `a^{x_0^y}`. The first line has the same expression correctly rendered, but on the second line the editor preview puts the `y` in the wrong place.

<img width="863" alt="kuva" src="https://user-images.githubusercontent.com/92814/127616924-f58c7bae-55e2-40bf-a023-55de6d238797.png">

**Comment by mplattu** [comment] 2021-08-10 08:26
The rendering shown on the left is rendered by MathQuill and this appears to be a bug in MathQuill. To reproduce:

1. Open [MathQuill homepage](http://mathquill.com/)
1. **Paste** the sample LaTeX code to the upmost text field (typing won't work)
1. Observe the rendered formula
![Screenshot_2021-08-10_11-22-37](https://user-images.githubusercontent.com/6679632/128833637-d1e8c187-07e9-46fb-a9a3-68187229878b.png)

The formula shown in the blue background is rendered using MathJax library. As you point out the MathJax does better job with this LaTeX code. This is also the version of the formula which will be  shown to the grading teachers and censors.

You're free to open an [MathQuill issue](https://github.com/mathquill/mathquill/issues).

Since this is not a bug in rich-text-editor itself I will close the issue. Thanks for contributing!

**Closed by mplattu** 2021-08-10 08:26 UTC
